language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev
  - pypy
  - pypy3

before_install:
  - SED_GET_PY='s/[^0-9]//g;s/.//3g;2s/.*/py/;1!G;h;$!d;s/y.2./y/;s/y.3./y3/'
  - PY=$(python -V 2>&1 | sed "$SED_GET_PY")
  - export TOXENV=py$PY
  - DEPS=tox

install:
  - pip install --upgrade $DEPS
  - pip list # Helpful when debugging
  - tox --notest

script:
  - tox

notifications:
    email: false
